# Generated by Django 5.1.3 on 2024-12-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweb", "0003_orderlist_orderdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
