# Generated by Django 5.1.3 on 2024-12-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweb", "0005_alter_orderlist_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="id",
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myweb.orderlist"
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="product_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
