# Generated by Django 5.1.3 on 2024-12-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweb", "0007_delete_orderdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=200)),
                ("product_type", models.CharField(max_length=100)),
                ("product_inventory", models.IntegerField()),
                ("product_position", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("package", models.CharField(max_length=255)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderlist_order_id",
                        to="myweb.orderlist",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderdetail_product_id",
                        to="myweb.product",
                    ),
                ),
                (
                    "product_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderdetail_product_name",
                        to="myweb.product",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderdetail_product_type",
                        to="myweb.product",
                    ),
                ),
            ],
        ),
    ]
