# Generated by Django 5.1.3 on 2024-12-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myweb", "0008_product_orderdetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderDetail",
        ),
    ]
