# Generated by Django 5.1.3 on 2024-12-13 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweb", "0010_orderdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_A", models.DateTimeField(blank=True, null=True)),
                ("process_B", models.DateTimeField(blank=True, null=True)),
                ("process_C", models.DateTimeField(blank=True, null=True)),
                ("complete", models.DateTimeField(blank=True, null=True)),
                ("duration_A", models.FloatField(blank=True, null=True)),
                ("duration_B", models.FloatField(blank=True, null=True)),
                ("duration_C", models.FloatField(blank=True, null=True)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_process_time",
                        to="myweb.orderlist",
                    ),
                ),
            ],
        ),
    ]
